// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestAPI.Models;

namespace RestAPI.Migrations
{
    [DbContext(typeof(DbManager))]
    [Migration("20181128075408_RestAPI.Models.DbManager")]
    partial class RestAPIModelsDbManager
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestAPI.Models.ShowCast", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Castid");

                    b.Property<int>("Showsid");

                    b.Property<DateTime?>("birthday");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.HasIndex("Showsid");

                    b.ToTable("ShowCast");
                });

            modelBuilder.Entity("RestAPI.Models.Shows", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ShowId");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("RestAPI.Models.ShowCast", b =>
                {
                    b.HasOne("RestAPI.Models.Shows")
                        .WithMany("showCasts")
                        .HasForeignKey("Showsid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
